### ISSUE TITLE
[Android] Platformview cannot be null

### ISSUE THREAD

**Issue by iamceejaygabrang** [zleao/zoft.MauiExtensions.AutoCompleteEntry#15]
When navigating to a page using tab bar that has autocompleteentry the app crashes. It says platformview cannot be null

**Comment by zeroniak** [comment]
I had the same problem. It worked the first time AutoCompleteEntry was shown, but not the second time. It debugged the code and it seemed to be in the DisconnectHandler method in AutoCompleteEntryHandler for Android.

It used the PlatformView property and not the platformView input parameter. I changed the code to use the platformView parameter instead and now it works on android. 
@zleao should ConnectHandler and DisconnectHandler perhaps use the parameter input instead of the property?

**Comment by iamceejaygabrang** [comment]
Can you provide a code snippet on how you change the code to use the platformView parameter? Thank you.

**Comment by daniel-luberda** [comment]
```
protected override void ConnectHandler(AndroidAutoCompleteEntry platformView)
{
    PlatformView.ViewAttachedToWindow += OnLoaded;
    PlatformView.TextChanged += AutoCompleteEntry_TextChanged;
    PlatformView.SuggestionChosen += AutoCompleteEntry_SuggestionChosen;
}

to

protected override void ConnectHandler(AndroidAutoCompleteEntry platformView)
{
    platformView.ViewAttachedToWindow += OnLoaded;
    platformView.TextChanged += AutoCompleteEntry_TextChanged;
    platformView.SuggestionChosen += AutoCompleteEntry_SuggestionChosen;
}
```

**Comment by khambley** [comment]
@daniel-luberda The code snippets are identical, am I missing something?

**Comment by daniel-luberda** [comment]
`PlatformView` vs `platformView` (letter cases) ;)

**Comment by khambley** [comment]
Is it autocompleting for you on Android? It's not working for me on Android API 31-34 .NET 8 emulators or physical devices.

**Comment by zleao** [comment]
Hello all.
Thank you for your continuous support and patience.
I managed to get some time to take a look at these issues.
I'm merging today the changes suggested by @zeroniak, to use `platformView`

@khambley I noticed as well that the suggestion box was not being updated while writing. I've updated the sample project to make it work again. I'll merge things today to main
